spring:
  application:
    name: Planify

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:9600/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    out-of-order: true
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    clean-disabled: true
    locations:
      - classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
